#!/usr/bin/python3
"""
a Python script that takes your GitHub credentials 
(username and password) and 
uses the GitHub API to display your id
"""
if __name__ == "__main__":
    import requests
    from sys import argv
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <url>", file=sys.stderr)
        exit(1)
    auth = HTTPBasicAuth(argv[3])
    response = requests.get("https://api.github.com/user", auth=auth)
    print(response.json().get("id"))
