#!/usr/bin/python3
import urllib
"""
a Python script that fetches https://alx-intranet.hbtn.io/status
"""
fetch = urllib.request.Request('https://alx-intranet.hbtn.io/status')
with urllib.request.urlopen(fetch) as response:
    the_page = response.read()
